options:
  http_port:
    type: string
    default: "8080"
    description: |
      HTTP-port.
  admin_username:
    type: string
    default: admin
    description: |
      Admin username.
  admin_password:
    type: string
    default: ""
    description: |
      Admin password.
  manager_enabled:
    type: boolean
    default: False
    description: |
      Enable this to be able to use the Manager web-app.
  cluster_enabled:
    type: boolean
    default: False
    description: |
      Enable session clustering.
