options:
  http-port:
    type: string
    default: "8080"
    description: |
      HTTP-port.
  manager-enabled:
    type: boolean
    default: False
    description: |
      Enable this to be able to use the Manager web-app.
  admin-username:
    type: string
    default: admin
    description: |
      Admin username.
  admin-password:
    type: string
    default: ""
    description: |
      Admin password.
  cluster-enabled:
    type: boolean
    default: False
    description: |
      Enable session clustering.
  install-type:
    type: string
    default: "full"
    description: |
      Type of install to perform. Valid options are 'jre' or 'full'. The
      default is 'jre', which will install the Java Runtime Environment
      (JRE). Setting this to 'full' will install the Java Development
      Kit (JDK) in addition to the JRE.
  java-major:
    type: string
    default: "8"
    description: |
      Major version of Java. Defaults to 8. Supported versions are 'Oracle java 8' and 'openjdk 6/7/8'
